# Travis CI integration
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

# Use docker for quicker builds, it now allows https://docs.travis-ci.com/user/apt/
sudo: false

# Test build with both GCC and Clang (LLVM)
compiler:
  - gcc
  - clang

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "HvCTpuitYJe0ew5cdHzEL0GLESnMMChI8Pv6XN3L33GykdSvYIgWf5RSX8gfRUMSit6oISfBwHY8sWDOEXs2L7O+QE7uaOdn/zF8Nmdo+7UHECI8ir5hUbMlZKA4dY6264hpnRJg9wQq9DE9vTzW9VydUs2X42cnZz3jA0x8A5A="

addons:
  apt:
    packages:
      - tree
  coverity_scan:
    project:
      name: "troglobit/watchdogd"
      description: "Watchdog daemon for embedded Linux systems with pmon API"
    notification_email: troglobit@gmail.com
    build_command_prepend: "./autogen.sh && PKG_CONFIG_PATH=/tmp/lib/pkgconfig ./configure"
    build_command:   "make clean all"
    branch_pattern: dev

install:
  - wget https://github.com/troglobit/libuev/releases/download/v1.4.0/libuev-1.4.0.tar.xz
  - wget https://github.com/troglobit/libite/releases/download/v1.5.0/libite-1.5.0.tar.xz
  - tar xf libuev-1.4.0.tar.xz
  - tar xf libite-1.5.0.tar.xz
  - (cd libuev-1.4.0 && ./configure --prefix=/tmp && make && make install-strip)
  - (cd libite-1.5.0 && ./configure --prefix=/tmp && make && make install-strip)

script:
  - ./autogen.sh
  - PKG_CONFIG_PATH=/tmp/lib/pkgconfig ./configure --prefix=/tmp --enable-examples
  - make clean
  - make V=1 -j5
  - make install-strip
  - tree /tmp
  - ldd /tmp/sbin/watchdogd
  - LD_LIBRARY_PATH=/tmp/lib /tmp/sbin/watchdogd -h
  - LD_LIBRARY_PATH=/tmp/lib ./testit.sh
