# Travis CI integration
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

# We don't need to install packages, use dockerized build, quicker
sudo: false

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "HvCTpuitYJe0ew5cdHzEL0GLESnMMChI8Pv6XN3L33GykdSvYIgWf5RSX8gfRUMSit6oISfBwHY8sWDOEXs2L7O+QE7uaOdn/zF8Nmdo+7UHECI8ir5hUbMlZKA4dY6264hpnRJg9wQq9DE9vTzW9VydUs2X42cnZz3jA0x8A5A="

addons:
  coverity_scan:
    project:
      name: "troglobit/watchdogd"
      description: "Watchdog daemon for embedded Linux systems with pmon API"
    notification_email: troglobit@gmail.com
    build_command: "make"
    branch_pattern: dev

install:
  - wget https://github.com/troglobit/libuev/releases/download/v1.4.0/libuev-1.4.0.tar.xz
  - wget https://github.com/troglobit/libite/releases/download/v1.5.0/libite-1.5.0.tar.xz
  - tar xf libuev-1.4.0.tar.xz
  - tar xf libite-1.5.0.tar.xz
  - (cd libuev-1.4.0 && ./configure --prefix=/tmp && make && make install-strip)
  - (cd libite-1.5.0 && ./configure --prefix=/tmp && make && make install-strip)

# We (currently) don't use GNU Configure & Build System, only a simple
# Makefile, for the time being.
script:
  - make distclean
  - prefix=/tmp make
  - prefix=/tmp make test
